CREATE TABLE DAT(VAL NUMBER(10));
INSERT INTO DAT VALUES(1200);
INSERT INTO DAT VALUES(1240);
INSERT INTO DAT VALUES(7200);
INSERT INTO DAT VALUES(1650);
INSERT INTO DAT VALUES(120);
INSERT INTO DAT VALUES(9754);
INSERT INTO DAT VALUES(0345);
INSERT INTO DAT VALUES(112);
INSERT INTO DAT VALUES(986);
INSERT INTO DAT VALUES(6478);
INSERT INTO DAT VALUES(9345);
INSERT INTO DAT VALUES(9632);
INSERT INTO DAT VALUES(223);
INSERT INTO DAT VALUES(1299);

SELECT * FROM DAT;
SELECT SUM(VAL) FROM DAT;
SELECT AVG(VAL) FROM DAT;
SELECT MIN(VAL) FROM DAT;
SELECT COUNT(*) FROM DAT;

SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MON-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MONTH-DAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YEAR-MONTH-DAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DDSP') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DL') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DL','NLS_DATE_LANGUAGE=HINDI') FROM DUAL;
--SELECT ENAME,HIREDATE TO_CHAR(HIREDATE,'Q') JOINED_QUARTER FROM EMP;

SELECT TO_DATE('16-OCT-2013') AS DATE_TEST FROM DUAL;
SELECT TO_DATE('16-10-3423','DD-MM-YYYY') AS DATE_TEST FROM DUAL;
SELECT TO_DATE('12-JAN-2011','DD-MON-YYYY') AS DATE_TEST FROM DUAL;