--rownum
select * from students;
SELECT * FROM STUDENTS WHERE ROWNUM<=5;
SELECT * FROM STUDENTS WHERE ROWNUM>1;     --IT WILL NOT WORK AS FIRST IT GIVES NUMBER TO ROW AND CONDITION IS NOT SATISFIED SO IT MOVES ON AND GIVES NEXT ROW NUMBER ONE AND SO ON AND THERE WILL BE NO RESULT
SELECT * FROM STUDENTS WHERE ROWNUM=1;     --IT WILL WORK AS IT GIVES NO TO ROW 1 AND CONDITION SATISFIES

select * from emp;
SELECT * FROM DEPT;
select sal from emp  where sal IN(select SAL from emp WHERE ROWNUM<=5);  --MAKE ERROR FREE

--SUBQUERY
SELECT * FROM EMP WHERE DEPTNO IN(SELECT DEPTNO FROM DEPT);
SELECT * FROM EMP WHERE ENAME IN 
