desc kani1;
rename kani1 to stu;
DESC STU;

CREATE TABLE STUDENT(
ROLLNO NUMBER(10),
SNAME VARCHAR(20),
SADDRESS VARCHAR2(20),
DOB DATE,
PHNO NUMBER(10)
);

DESC STUDENT;

INSERT INTO STUDENT VALUES(11,'ARTHUR','VALENTINE','11-MAR-12',7865425323);
INSERT INTO STUDENT VALUES(11,'HINATA','BILASPUR','2-AUG-45',786523234);
INSERT INTO STUDENT VALUES(13,'SAKUNA','KASOLI','28-MAR-10',786542376);
INSERT INTO STUDENT VALUES(14,'GOJO','SHIMLA','10-FEB-12',786542344);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE ROLLNO=113;
INSERT INTO STUDENT(ROLLNO,SNAME)VALUES(104,'SASUKE');
INSERT INTO STUDENT VALUES(&ROLLNO,&SNAME,&SADDRES,&DOB,&PHNO);

DELETE FROM STUDENT WHERE SNAME='SASUKE';

update student set rollno=rollno+100;
UPDATE STUDENT SET SNAME=NULL WHERE ROLLNO=111;

DELETE FROM STUDENT WHERE ROLLNO=111;

CREATE TABLE KANI1(ROLL NUMBER(10));
DESC KANI1;
DROP TABLE KANI1;

//ALIASING COLUMNS
SELECT SNAME AS "StuNAME" FROM STUDENT;
SELECT ROLLNO "rOLL",SNAME AS naME FROM STUDENT;

SELECT * FROM STUDENT WHERE ROLLNO>112;
SELECT ROLLNO,DOB,PHNO FROM STUDENT WHERE SNAME='SASUKE' AND ROLLNO>='114';

--CREATING COPY OF TABLE
CREATE TABLE STUD AS(SELECT * FROM STUDENT);
CREATE TABLE SHALLOWSTUD AS(SELECT * FROM STUDENT WHERE 1=2);   --MAKE A SHALLOW TABLE 
CREATE TABLE EMP AS(SELECT ROLLNO AS EMPLOYEENO,SNAME AS EMPNAME,SADDRESS,DOB,PHNO FROM STUDENT);    --CREATING A TABLE WITH DIFFRENT COLUMN NAMES
SELECT * FROM SHALLOWSTUD;
SELECT * FROM EMP;
SELECT * FROM STUD;
DROP TABLE STUD;

--COPYING DATA FROM ONE TABLE TO ANOTHER
INSERT INTO SHALLOWSTUD(ROLLNO,SNAME) SELECT ROLLNO,SNAME FROM STUDENT;
